spring:
  application:
    name: plataforma-avaliacoes-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/plataforma_avaliacoes}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8081}

app:
  cors:
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*,http://[::1]:*}
  services:
    gabarito-url: ${GABARITO_SERVICE_URL:http://localhost:8001}

jwt:
  secret: ${JWT_SECRET:EsteEhUmSegredoMuitoLongoParaJWTQuePrecisaTerPeloMenos256BitsParaSerSeguro}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
